spring.application.name=notificationsystembackend
# ===============================
# = SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# = DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/cns
spring.datasource.username=root
spring.datasource.password=00001
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# = JWT
# ===============================
jwt.secret=aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789abcdefghijklmnopqrstuvwxyz+/ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789==
jwt.expiration=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=singhtanishq288@gmail.com
spring.mail.password=xdumzmxjtcghxtpy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8


dropbox.access-token=sl.u.AGPcwW9nvK5WMjjJi2qkAIirxe-sZ_qAancBgsvVwAx5Rcr6C0hw9VtfnN_xo-SCmHBeG_eLKcdGEG7DykFJwohX-1TZn8tCVgbnWVKBWbKBsMVAEKzxbtOGYzgxUdLzw5lu7LCaQ1PP9MmFO5JInN0TCUD6fR8CdKAYt-TNQuGxndmdKd2e8uJbkfNcrFjLNmJP9PVjdTK5WUlPXFtxmrWQ_MYQP1w1PN55VLYiI78zjt4WawEoBMxuSV0mB8NVQ-HpZ5ZtyrjZmBve4qrXVWQYLkTykU5uY21a-qo2jvd5Tm9fOG0ssVLlCv3SUxd_LpuhVrhtgHAJ7YUN6444c5y-oA_oZDPMgngisZK0v3gsuD9BJrDO4ibOn3pEAtWbi-CCk2az7lu1KuofFFlsqivmEXKN6eAmC0cwY5jc572tm4KfIrX3vsvatBhHhjhq308eAaoUfsmMi5LGBq5FPr7Cti07Mtke-j0Xil5fEzttZzht4XctUy87KKit-hibOaYzZYz1eBgGnu0xLHscIjS8hnCC3sHNBvc9g-BLEGW5Hwma8FoiSe9IHlWOTYkVFwlkCIOyAu1z_xXnELZKPUHI20iR88lK4KnXWnQc8Zd3R60yWyDo6NAR9BaLcPCV-rXujtm3riXdEqKc3rQBqaKaejUvJd5tbrJLyx8gM2JvB77kN5pg_ajaQSFurgRiLsfntLpmTO3wKTw0iKvu0a4VSJe-RiEou9W5Qty_c9kMkS2jZIkA0ub1tGtYG6gXErWEv4ttTGy_qqzGpcKiFDJgJBlg8RMjOb50fcAeOpLROcjoIqOa5EMG8QEzm5sX1O8q4XUszhmONB6FOkGpRJuMztEtfYaR3mb7usOgMWNjvCXw5chYg5EVrYh2z2l0S3JGDoxB3CoQYEUYQbF3cS-ULdJqY7GiACqJHVm8CIFUXJ2tVfqYOVnzgRr6LD08UmPuYV4Xyf3Jgm_1sXnlPrsZCkYG_dlF2KpraOkzw9GdoxgyDEj-32bcf8OcmY8uXGrf_QX2RpaGaSWgiZ5QDQi-xKBa_e_Nnykzc5G1iZqPfkzyDK8PLq9MJga7TioOVW8R22LoXB5ibN3XGGBHwVM8e5u4CUxy8qczz-KcDLnFV2nGBANrXCMDTGSvkJhQG7_x3CyBB6c5KhrGNWo2OIROAV4PCpgrp_ZB34bxYy7swmX9y4GS7TTQb-kjTEkkGpUurBHquyuNyosICbGwIMZDt1dL1rUZeYm1mBLh7rWkBRXBMOO7bzvC3uOrBGHFlhejrPcqAafEkx0daErbBnLz_NCvouKX44fMtSks1X_AowBZmZIUB7UnwA-vGPGmxhLaXO6VklQuVyfxULBB7SOeaes-z8vshVUz9t5Qh3z3ISJMCCec4nDF12QykHPOxUMRgu9Rdyu5q2AijWEudeh8FhRlV77N8M-R2Vdy4OS-IQ
dropbox.folder=/notices
