spring.application.name=notificationsystembackend
# ===============================
# = SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# = DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/cns
spring.datasource.username=root
spring.datasource.password=00001
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# = JWT
# ===============================
jwt.secret=aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789abcdefghijklmnopqrstuvwxyz+/ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789==
jwt.expiration=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=singhtanishq288@gmail.com
spring.mail.password=xdumzmxjtcghxtpy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8


dropbox.access-token=sl.u.AGOy-vPGhb00uHPxmIvudbrc6WukHQd_ChIWiUTMNRdMJpRCGV90iSM6iQom3UOdzblg4g-A34m70mQ1i6ynBWP-VoqaC6vUvJAgSssldcDr2vfxl71AVVlOiHf00OyTFLiQ5sRbeeUPxFJ4tlThy2IssZgamFqa3mf1THsxKy7Opv9n5rMmCsfVhxdfpETaYSWABkfFcUJ4-fWpDNgqV0bJm6gYjoj3btIaExKI8MalJiglsXYHTez364ggrSWBTQowqMraYmxtIjXJ63PXW56_oY87IfkClFkDGILOqVZekVeC1oGBrlLCqSCiFQCMZAeCpQED61abclTUMPjRFbfL-PwBNgW8j5Nq8XuSKyP9txO--QgnWgl1ufwnOhHHHsADHln9sdSM4HJWz7uQznPToctOw0Rb5jkNjBoKahuvCMzFpZtUS6JP5rykV8zbJDT--KmqEobevMdHUuXL7b8NpyHMeJIUP7cdW-ZPmbLB2fMVp8ayx5hRPtbtuXjEdjBixdjj-C1CqoumVLVYVNN3TR3qIS_p6X4y4tiPyAItEzXO4ekL3Mk0onGWu_s1TBclnp489gyxBeau5TIuay10PSrkt3h9RiU2fAOS117gaOi-AjPCsr2efZBdbb6krb_os0hvfcZcFLOBcR085a_QlqFUnYeBJvNkM6fZXoPYlsNJtv2pyXVn4e9hNuWFaUhQDS5Xa5A4UpUD0CgqnbY2FtUlKTduJhtVwRfLBeGIeORWArYf5kukHBAhj0dPamW6yZMnf89GPVD6gTMG2tE9oBvL0-hq4Sv89ygA_Z_ZVC-gX0I52uFi32KBiDi0VR5Wtf8r3d9WXNVOyvSusE1NCfXIjJ0LUfagzIzF2QhMc4CkvsPgzVA5cv0TLxtwAojSunUNFlkzX74EMyxz-3SriMrF_ECPycl4ue2wzfO9GWdt-PJYY0bKkoHYt1209zrs5wvVzbMDfdi6hQHnuIE1wmowrBn80c0UBgOwDQl8M08weKRgDv1Mkba2U-p-w9kHlnOAW5p2rRwS8Cm1h7zUNIhXHqAmOhIqv-Zl_4UEPMRJFn-4aLcU5YN5qQAaQUHx7YT39moc8BeDQnDjNNhJuAiedatXHxBVEP6hYrOL8PveSQK1GuXfwBJzBZWJM9N7bK4jpvLgcUUcViOs7kawKFshaS6_IAFG85DacxVEzpWJC-CVvXa0ieKlXkj0sGWcxn-1NP93wqKByS5MYabV8R4-IZHfbevFrVIy0honF1WiELQGuyde0L8k1oIsWpGcAnkYgxtDvgoDj7Dvvp3uxpKLjabJs_C47LdqYieHZTcdWRJj6eX-Y4m8836gJXpolek6-x7RD-jWP-jAF9l2A_AVjGjakmwH_5jdDSTjchxnHhCFHSUtK6mhk99D_w9iJwWL2RXtWZXWyiO9Y_8moUzOOqc07gbCnvkqaQeEcg



dropbox.folder=/notices
