spring.application.name=notificationsystembackend
# ===============================
# = SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# = DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://mysql-ab9a776-singhtanishq288-ba1e.i.aivencloud.com:11263/defaultdb?useSSL=true&requireSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_Au69xHYHORBOBNmHJNO
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver






# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# = JWT
# ===============================
jwt.secret=aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789abcdefghijklmnopqrstuvwxyz+/ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789==
jwt.expiration=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=singhtanishq288@gmail.com
spring.mail.password=xdumzmxjtcghxtpy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8


dropbox.access-token=sl.u.AGN2tmJVIu2pFNd_iqGobFgblSy0IA1SqYfdiKjYdpsyGLpqSRSeUwzVNwapk5ibdmoVxoQUXkBVrWWdJCKIzvAd_DBEh4T_tB-XKUkF-Gabr6Jps7Ba8t0jcuqS1oQynvCMl00snvAtj2A8HlO-nlzS11ruiIdofbMvSZaTAXj7IcNAGvUihPR0mGmKgtFw6mASXbrKhpqh1oxMN28nB6B9IqGllgdHjaGre1czS_UfV9Ra0W2YrksMXPw1vw_ilgLy5p3-aGJEQrb_9vdwm9SG6L_vQcJkkk_PmVhFok1gS1Hcvzy0nBkCK7evdh8zMxc1W8wCECAw0H4TDpcbybV-9UZ7VrnRJbemNMFSWIBuciASCspRcx-ATU2_6YMbZmrlPCT2ZTILhSIME-GsJX2x1Tc8eJYlW7FUtlmb924iRExOuoHyBxNx9IiesYJ-bGvvDRZm_rvhOehOaAw2gixiLbpbeSUvAvawou9WECwzHd94QUA-SZxFuFqg-_W5pCxje-YvF5TzEqZJ1N4UgcY5VElkxVeZ6-D7r_DAZvbaCOvaswwanwRWp_x6Pxqb27f1WImpQQgnZh5E45az16CB7GN-qXO632IjwxdYz9U4f3RjOI-4_J_SfYJfOXGCwr_UCuL1dQtvDCOwQSWB2B2uqKMCc4Wem2CUBlMvGPmCqHaWJ8NH0G85EpeCueFeqOtpwO9E58FHSACvwBpIC0o2zPYZ8bi82BQKCmzHwM7MP_ucnxdCDsXfWoNgJMFcuNWcltcS8N6t96udV0NHqtAFDPkzVXc76KjRURTfTqDcGtGoi4NSIGSRv8e6e69-IQVTtUxLZ3UgSI0ToIh8jJJygxdfJgAvvxBS_iBw4kPq7MEyGw4zDziQLjIuN4I0_vZcWPvJNx2xYUCBa94Echv5Vl1g5SJ88rCJAoN1iZP6K8CexkzpCnD8DMJZg5nHLs1RlfS0XiXV3jk3goazRa3Vm2b9aB_WX_loEcr2IOPaqHUDmKORvD26wn5cwdea6Vx_u_CtjcJ95HjuX4LTqIgRrVS7NYrwt32CwxBBoGU8c3wdG143KYTf8Oe_GaPR0My-dBxKXAu6dHfm3D0OaOloiqRcJHvU03icw0r_dws03r1aqpBsynBUsNkRwKfxR5KNDJRl7f_zc_9kpLMprJvYuBUvtIuKgBYXEsJ2U8E-JIU6KCzcZTMpbNLU5usicKIbRna_dCquLhx2R3VNcMwLLsaGcU63iLFZXRV3X_6UixzgBqN-XHHhHbV90sf0YG-8Nw0TWN-jKptLd6juI7WBfiAHo3kVT_dpy-Ti22cJqN1r7f5PWRFkK4eQ8FPl_NLB3zfuTP7CMOlq3UnLNDayix0L0svVuRn3gVhR3HZ4LxVAF3Gr5WJxsBCzJBPtIPyz0JAw9tsl7ACUr_sqMBd6ijnitG7DTHDtM-BebgdEAQ


dropbox.folder=/notices
